-- MySQL Script generated by MySQL Workbench
-- 11/26/16 21:05:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BDPlanificaMYPE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDPlanificaMYPE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDPlanificaMYPE` DEFAULT CHARACTER SET utf8 ;
USE `BDPlanificaMYPE` ;

-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`TipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`TipoDocumento` (
  `idTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Zona` (
  `idZona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `urbanizacion` VARCHAR(50) NOT NULL,
  `montoFlete` DOUBLE NOT NULL,
  PRIMARY KEY (`idZona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NULL,
  `apellidoPaterno` VARCHAR(100) NULL,
  `apellidoMaterno` VARCHAR(100) NULL,
  `razonSocial` VARCHAR(100) NULL,
  `numeroDocumento` VARCHAR(20) NOT NULL,
  `fechaNacimiento` DATETIME NULL,
  `genero` TINYINT(1) NULL,
  `telefono` VARCHAR(20) NULL,
  `correo` VARCHAR(100) NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `referencia` VARCHAR(100) NULL,
  `credito` TINYINT(1) NOT NULL,
  `idTipoDocumento` INT NOT NULL,
  `idZona` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `FK_Cliente_TipoDocumento`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `BDPlanificaMYPE`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Cliente_Zona`
    FOREIGN KEY (`idZona`)
    REFERENCES `BDPlanificaMYPE`.`Zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Cliente_TipoDocumento_idx` ON `BDPlanificaMYPE`.`Cliente` (`idTipoDocumento` ASC);

CREATE INDEX `FK_Cliente_Zona_idx` ON `BDPlanificaMYPE`.`Cliente` (`idZona` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Empleado` (
  `idEmpleado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidoPaterno` VARCHAR(100) NOT NULL,
  `apellidoMaterno` VARCHAR(100) NOT NULL,
  `numeroDocumento` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(100) NULL,
  `estado` VARCHAR(50) NOT NULL,
  `sueldo` DOUBLE NOT NULL,
  `licencia` VARCHAR(50) NULL,
  `fechaIngreso` DATETIME NOT NULL,
  `fechaSalida` DATETIME NULL,
  `idCargo` INT NOT NULL,
  `idTipoDocumento` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `FK_Empleado_TipoDocumento`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `BDPlanificaMYPE`.`TipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Empleado_Cargo`
    FOREIGN KEY (`idCargo`)
    REFERENCES `BDPlanificaMYPE`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Empleado_TipoDocumento_idx` ON `BDPlanificaMYPE`.`Empleado` (`idTipoDocumento` ASC);

CREATE INDEX `FK_Empleado_Cargo_idx` ON `BDPlanificaMYPE`.`Empleado` (`idCargo` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `fechaRegistro` DATETIME NOT NULL,
  `fechaEnvio` DATETIME NOT NULL,
  `montoTotal` DOUBLE NOT NULL,
  `montoPagado` DOUBLE NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  `telefono` VARCHAR(15) NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `referencia` VARCHAR(200) NULL,
  `idZona` INT NOT NULL,
  `idCliente` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  CONSTRAINT `FK_Pedido_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `BDPlanificaMYPE`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Pedido_Empleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `BDPlanificaMYPE`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Pedido_Zona`
    FOREIGN KEY (`idZona`)
    REFERENCES `BDPlanificaMYPE`.`Zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Pedido_Cliente_idx` ON `BDPlanificaMYPE`.`Pedido` (`idCliente` ASC);

CREATE INDEX `FK_Pedido_Empleado_idx` ON `BDPlanificaMYPE`.`Pedido` (`idEmpleado` ASC);

CREATE INDEX `FK_Pedido_Zona_idx` ON `BDPlanificaMYPE`.`Pedido` (`idZona` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Marca` (
  `idMarca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`TipoCarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`TipoCarga` (
  `idTipoCarga` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idTipoCarga`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`UnidadMedida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`UnidadMedida` (
  `idUnidadMedida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUnidadMedida`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Articulo` (
  `idArticulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `precioBase` DOUBLE NOT NULL,
  `stock` DOUBLE NOT NULL,
  `volumen` DOUBLE NOT NULL,
  `tiempoHorasAbastecer` INT NULL,
  `combinable` TINYINT(1) NOT NULL,
  `minimoDivisible` DOUBLE NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `idMarca` INT NOT NULL,
  `idTipoCarga` INT NOT NULL,
  `idUnidadMedida` INT NOT NULL,
  PRIMARY KEY (`idArticulo`),
  CONSTRAINT `FK_Articulo_Marca`
    FOREIGN KEY (`idMarca`)
    REFERENCES `BDPlanificaMYPE`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Articulo_TipoCarga`
    FOREIGN KEY (`idTipoCarga`)
    REFERENCES `BDPlanificaMYPE`.`TipoCarga` (`idTipoCarga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Articulo_UnidadMedida`
    FOREIGN KEY (`idUnidadMedida`)
    REFERENCES `BDPlanificaMYPE`.`UnidadMedida` (`idUnidadMedida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Articulo_Marca_idx` ON `BDPlanificaMYPE`.`Articulo` (`idMarca` ASC);

CREATE INDEX `FK_Articulo_TipoCarga_idx` ON `BDPlanificaMYPE`.`Articulo` (`idTipoCarga` ASC);

CREATE INDEX `FK_Articulo_UnidadMedida_idx` ON `BDPlanificaMYPE`.`Articulo` (`idUnidadMedida` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`DetallePedido` (
  `idPedido` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `cantidadAtendida` DOUBLE NOT NULL,
  `precioUnitario` DOUBLE NOT NULL,
  `monto` DOUBLE NOT NULL,
  PRIMARY KEY (`idPedido`, `idArticulo`),
  CONSTRAINT `FK_DetallePedido_Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `BDPlanificaMYPE`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DetallePedido_Articulo`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `BDPlanificaMYPE`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_DetallePedido_Articulo_idx` ON `BDPlanificaMYPE`.`DetallePedido` (`idArticulo` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`TipoVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`TipoVehiculo` (
  `idTipoVehiculo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idTipoVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`MarcaVehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`MarcaVehiculo` (
  `idMarcaVehiculo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idMarcaVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Vehiculo` (
  `idVehiculo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `anio` VARCHAR(50) NULL,
  `modelo` VARCHAR(50) NULL,
  `placa` VARCHAR(50) NULL,
  `idMarcaVehiculo` INT NOT NULL,
  `idTipoVehiculo` INT NOT NULL,
  PRIMARY KEY (`idVehiculo`),
  CONSTRAINT `FK_Vehiculo_TipoVehiculo`
    FOREIGN KEY (`idTipoVehiculo`)
    REFERENCES `BDPlanificaMYPE`.`TipoVehiculo` (`idTipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Vehiculo_MarcaVehiculo`
    FOREIGN KEY (`idMarcaVehiculo`)
    REFERENCES `BDPlanificaMYPE`.`MarcaVehiculo` (`idMarcaVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Vehiculo_TipoVehiculo_idx` ON `BDPlanificaMYPE`.`Vehiculo` (`idTipoVehiculo` ASC);

CREATE INDEX `FK_Vehiculo_MarcaVehiculo_idx` ON `BDPlanificaMYPE`.`Vehiculo` (`idMarcaVehiculo` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Viaje` (
  `idViaje` INT NOT NULL AUTO_INCREMENT,
  `fechaRegistro` DATETIME NOT NULL,
  `fechaSalida` DATETIME NULL,
  `fechaRetorno` DATETIME NULL,
  `estado` VARCHAR(50) NOT NULL,
  `idVehiculo` INT NULL,
  `idEmpleado` INT NULL,
  `idTipoVehiculo` INT NOT NULL,
  PRIMARY KEY (`idViaje`),
  CONSTRAINT `FK_Viaje_Empleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `BDPlanificaMYPE`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Viaje_Vehiculo`
    FOREIGN KEY (`idVehiculo`)
    REFERENCES `BDPlanificaMYPE`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Viaje_TipoVehiculo`
    FOREIGN KEY (`idTipoVehiculo`)
    REFERENCES `BDPlanificaMYPE`.`TipoVehiculo` (`idTipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Viaje_Empleado_idx` ON `BDPlanificaMYPE`.`Viaje` (`idEmpleado` ASC);

CREATE INDEX `FK_Viaje_Vehiculo_idx` ON `BDPlanificaMYPE`.`Viaje` (`idVehiculo` ASC);

CREATE INDEX `FK_Viaje_TipoVehiculo_idx` ON `BDPlanificaMYPE`.`Viaje` (`idTipoVehiculo` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`PedidoXViaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`PedidoXViaje` (
  `idPedido` INT NOT NULL,
  `idViaje` INT NOT NULL,
  `montoCobrado` DOUBLE NULL,
  `fechaAlmacen` DATETIME NULL,
  `fechaUbicado` DATETIME NULL,
  `fechaEntrega` DATETIME NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`idPedido`, `idViaje`),
  CONSTRAINT `FK_PedidoXViaje_Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `BDPlanificaMYPE`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PedidoXViaje_Viaje`
    FOREIGN KEY (`idViaje`)
    REFERENCES `BDPlanificaMYPE`.`Viaje` (`idViaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_PedidoXViaje_Viaje_idx` ON `BDPlanificaMYPE`.`PedidoXViaje` (`idViaje` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`DetalleViaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`DetalleViaje` (
  `idPedido` INT NOT NULL,
  `idViaje` INT NOT NULL,
  `idArticulo` INT NOT NULL,
  `cantidad` DOUBLE NOT NULL,
  `cantidadDescargado` DOUBLE NOT NULL,
  PRIMARY KEY (`idPedido`, `idViaje`, `idArticulo`),
  CONSTRAINT `FK_DetalleViaje_Articulo`
    FOREIGN KEY (`idArticulo`)
    REFERENCES `BDPlanificaMYPE`.`Articulo` (`idArticulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DetalleViaje_PedidoXViaje_2`
    FOREIGN KEY (`idViaje`)
    REFERENCES `BDPlanificaMYPE`.`PedidoXViaje` (`idViaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DetalleViaje_PedidoXViaje_1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `BDPlanificaMYPE`.`PedidoXViaje` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_DetalleViaje_Articulo_idx` ON `BDPlanificaMYPE`.`DetalleViaje` (`idArticulo` ASC);

CREATE INDEX `FK_DetalleViaje_viaje_idx` ON `BDPlanificaMYPE`.`DetalleViaje` (`idViaje` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (
  `idTipoVehiculo` INT NOT NULL,
  `idTipoCarga` INT NOT NULL,
  `volumen` DOUBLE NULL,
  PRIMARY KEY (`idTipoVehiculo`, `idTipoCarga`),
  CONSTRAINT `FK_TipoVehiculoXTipoCarga_TipoVehiculo`
    FOREIGN KEY (`idTipoVehiculo`)
    REFERENCES `BDPlanificaMYPE`.`TipoVehiculo` (`idTipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TipoVehiculoXTipoCarga_TipoCarga`
    FOREIGN KEY (`idTipoCarga`)
    REFERENCES `BDPlanificaMYPE`.`TipoCarga` (`idTipoCarga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_TipoVehiculoXTipoCarga_TipoCarga_idx` ON `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoCarga` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`TipoVehiculoXZona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`TipoVehiculoXZona` (
  `idTipoVehiculo` INT NOT NULL,
  `idZona` INT NOT NULL,
  `Disponible` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idTipoVehiculo`, `idZona`),
  CONSTRAINT `FK_TipoVehiculoXZona_Zona`
    FOREIGN KEY (`idZona`)
    REFERENCES `BDPlanificaMYPE`.`Zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_TipoVehiculoXZona_TipoVehiculo`
    FOREIGN KEY (`idTipoVehiculo`)
    REFERENCES `BDPlanificaMYPE`.`TipoVehiculo` (`idTipoVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_TipoVehiculoXZona_Zona_idx` ON `BDPlanificaMYPE`.`TipoVehiculoXZona` (`idZona` ASC);


-- -----------------------------------------------------
-- Table `BDPlanificaMYPE`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDPlanificaMYPE`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `idEmpleado` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_Usuario_Empleado`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `BDPlanificaMYPE`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Usuario_Empleado_idx` ON `BDPlanificaMYPE`.`Users` (`idEmpleado` ASC);

CREATE UNIQUE INDEX `usuario_UNIQUE` ON `BDPlanificaMYPE`.`Users` (`usuario` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`TipoDocumento`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`TipoDocumento` ( `nombre`, `descripcion`) VALUES ( 'DNI', 'Documento nacional de identidad de un ciudadano peruano');
INSERT INTO `BDPlanificaMYPE`.`TipoDocumento` ( `nombre`, `descripcion`) VALUES ( 'Pasaporte', 'Documento de identificación para los extranjeros');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`Zona`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`Zona` ( `nombre`, `urbanizacion`, `montoFlete`) VALUES ( 'Casa blanca', 'Casa blanca', 15);
INSERT INTO `BDPlanificaMYPE`.`Zona` ( `nombre`, `urbanizacion`, `montoFlete`) VALUES ( 'Montenegro', 'Montenegro', 20);
INSERT INTO `BDPlanificaMYPE`.`Zona` ( `nombre`, `urbanizacion`, `montoFlete`) VALUES ( 'Cristo rey bajo', 'Cristo rey', 10);
INSERT INTO `BDPlanificaMYPE`.`Zona` ( `nombre`, `urbanizacion`, `montoFlete`) VALUES ( 'Cristo rey alto', 'Cristo rey', 15);
INSERT INTO `BDPlanificaMYPE`.`Zona` ( `nombre`, `urbanizacion`, `montoFlete`) VALUES ( '10 de octubre', '10 de octubre', 20);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`Cargo`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`Cargo` ( `nombre`, `descripcion`) VALUES ( 'Administrador del sistema', 'Persona que administra el sistema de informacion.');
INSERT INTO `BDPlanificaMYPE`.`Cargo` ( `nombre`, `descripcion`) VALUES ( 'Supervisor', 'Persona que se encarga de la planificacion de los pedidos');
INSERT INTO `BDPlanificaMYPE`.`Cargo` ( `nombre`, `descripcion`) VALUES ( 'Recepcionista', 'Persona que registra los nuevos pedidos ');
INSERT INTO `BDPlanificaMYPE`.`Cargo` ( `nombre`, `descripcion`) VALUES ( 'Chofer', 'Persona que se encarga de enviar los pedidos al cliente');


COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`Empleado`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`Empleado` ( `nombres`, `apellidoPaterno`, `apellidoMaterno`, `numeroDocumento`, `correo`, `estado`, `sueldo`, `licencia`, `fechaIngreso`, `fechaSalida`, `idCargo`, `idTipoDocumento`) 
									VALUES ( 'Henry Antonio', 'Espinoza', 'Torres', '46618582', 'henryespinozat@gmail.com', 'Activo', 500, NULL, '2016-05-01', NULL, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`Marca`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Otro');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Sol');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Andino');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Matusita');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Nicoll');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Molina');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Huachipa');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Lark');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Aceros arequipa');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Eternit');
INSERT INTO `BDPlanificaMYPE`.`Marca` ( `nombre`) VALUES ( 'Generico');


COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`TipoCarga`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`TipoCarga` ( `nombre`, `descripcion`) VALUES ( 'Carga normal', 'Es la carga que va en la tolva del camion');
INSERT INTO `BDPlanificaMYPE`.`TipoCarga` ( `nombre`, `descripcion`) VALUES ( 'Carga pequeña', 'Es la carga de poco volumen que puede ser transportado en la cabina.');
INSERT INTO `BDPlanificaMYPE`.`TipoCarga` ( `nombre`, `descripcion`) VALUES ( 'Carga aerea', 'Es la carga que va en la superior de la tolva.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`UnidadMedida`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`UnidadMedida` ( `nombre`) VALUES ( 'kg');
INSERT INTO `BDPlanificaMYPE`.`UnidadMedida` ( `nombre`) VALUES ( 'm3');
INSERT INTO `BDPlanificaMYPE`.`UnidadMedida` ( `nombre`) VALUES ( 'bolsa');
INSERT INTO `BDPlanificaMYPE`.`UnidadMedida` ( `nombre`) VALUES ( 'varilla');
INSERT INTO `BDPlanificaMYPE`.`UnidadMedida` ( `nombre`) VALUES ( 'unidad');
INSERT INTO `BDPlanificaMYPE`.`UnidadMedida` ( `nombre`) VALUES ( 'lata');
INSERT INTO `BDPlanificaMYPE`.`UnidadMedida` ( `nombre`) VALUES ( 'balon');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`TipoVehiculo`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculo` ( `nombre`, `descripcion`) VALUES ( 'Camioneta pequeña', NULL);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculo` ( `nombre`, `descripcion`) VALUES ( 'Camioneta normal', NULL);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculo` ( `nombre`, `descripcion`) VALUES ( 'Camioneta grande', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`MarcaVehiculo`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`MarcaVehiculo` ( `nombre`) VALUES ( 'otro');
INSERT INTO `BDPlanificaMYPE`.`MarcaVehiculo` ( `nombre`) VALUES ( 'toyota');
INSERT INTO `BDPlanificaMYPE`.`MarcaVehiculo` ( `nombre`) VALUES ( 'mitsubishi');
INSERT INTO `BDPlanificaMYPE`.`MarcaVehiculo` ( `nombre`) VALUES ( 'izuzu');
INSERT INTO `BDPlanificaMYPE`.`MarcaVehiculo` ( `nombre`) VALUES ( 'volvo');
INSERT INTO `BDPlanificaMYPE`.`MarcaVehiculo` ( `nombre`) VALUES ( 'suzuki');
INSERT INTO `BDPlanificaMYPE`.`MarcaVehiculo` ( `nombre`) VALUES ( 'isuzu');

COMMIT;


-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (1, 1, 2);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (1, 2, 0.01);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (1, 3, 1);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (2, 1, 3);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (2, 2, 0.01);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (2, 3, 1.5);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (3, 1, 4);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (3, 2, 0.01);
INSERT INTO `BDPlanificaMYPE`.`TipoVehiculoXTipoCarga` (`idTipoVehiculo`, `idTipoCarga`, `volumen`) VALUES (3, 3, 1.7);

COMMIT;

-- -----------------------------------------------------
-- Data for table `BDPlanificaMYPE`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `BDPlanificaMYPE`;
INSERT INTO `BDPlanificaMYPE`.`Users` ( `name`, `usuario`, `password`, `remember_token`, `idEmpleado`) VALUES ( '46618582', '46618582', '$2y$10$wezuiI.XdVAMmAowTqtvVe9OSJSAx3r4rdhBeg7ehskeIJPwaJ446', NULL, 1);

COMMIT;